import dotenv from "dotenv";
dotenv.config();

const ENV = process.env;

// enviornments
const PORT = ENV.PORT;
const CLIENT_URL = ENV.CLIENT_URL;
const NODE_ENV = ENV.NODE_ENV;
const MONGODB_URI = ENV.MONGODB_URI;
const MONGODB_USERNAME = ENV.MONGODB_USERNAME;
const MONGODB_PASSWORD = ENV.MONGODB_PASSWORD;
const JWT_SECRET = ENV.JWT_SECRET;
const JWT_EXPIRES_IN = ENV.JWT_EXPIRES_IN;
const CLOUDINARY_CLOUD_NAME = ENV.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = ENV.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = ENV.CLOUDINARY_API_SECRET;

export {
  PORT,
  NODE_ENV,
  MONGODB_PASSWORD,
  MONGODB_URI,
  MONGODB_USERNAME,
  JWT_EXPIRES_IN,
  JWT_SECRET,
  CLIENT_URL,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_SECRET,
};
